version: '3'
services:
  server:
    build:
      context: ./websocket-server
    ports:
      - "3001:3001"
    networks:
      - mynetwork

  client:
    build:
      context: ./client-app
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL=http://server:3001
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

