version: '3'
services:

  flask-server:
    build:
      context: ./applications/flask_server  # Assuming your Flask app code is in a folder named 'flask-app'
    environment:
      - FLASK_SERVER_URL=http://127.0.0.1:3001
    ports:
      - "3001:3001"  # Exposing port 3001 for the Flask server
    networks:
      - mynetwork

  server:
    build:
      context: ./websocket-server
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  client:
    build:
      context: ./client-app
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER_URL=http://server:3001
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

