services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - FLASK_APP=flask_app.py
      - FLASK_RUN_HOST=0.0.0.0
      - EXPERIMENT_NAME=watsonx_insurance_claims_experiment
      - GRAPHSIGNAL_API_KEY=7e6ff4494810b4cb37255d369cfae983
      - OPENAI_API_KEY=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
      - API_URL=http://172.19.0.3:3001
      - OPENAI_ORG_ID=org-zvKGqHl0adRlJbe7lpb7n1wX
      - DB_HOST=172.19.0.2
      - REACT_APP_WEBSOCKET_URL=ws://172.19.0.4:8080
      - REACT_APP_API_URL=http://172.19.0.3:3001
      - FLASK_SERVER_URL=http://172.19.0.3:3001
      - DB_NAME=roja_postgres
      - DB_USER=roja_user
      - DB_PASSWORD=roja_user
      - DB_HOST=172.19.0.2
      - DB_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      custom_network:
        ipv4_address: 172.19.0.2

  flask_app:
    build:
      context: . 
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=flask_app.py
      - FLASK_RUN_HOST=0.0.0.0
      - EXPERIMENT_NAME=watsonx_insurance_claims_experiment
      - GRAPHSIGNAL_API_KEY=7e6ff4494810b4cb37255d369cfae983
      - OPENAI_API_KEY=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
      - API_URL=http://172.19.0.3:3001
      - OPENAI_ORG_ID=org-zvKGqHl0adRlJbe7lpb7n1wX
      - DB_HOST=172.19.0.2
      - REACT_APP_WEBSOCKET_URL=ws://172.19.0.4:8080
      - REACT_APP_API_URL=http://172.19.0.3:3001
      - FLASK_SERVER_URL=http://172.19.0.3:3001
      - DB_NAME=roja_postgres
      - DB_USER=roja_user
      - DB_PASSWORD=roja_user
      - DB_HOST=172.19.0.2
      - DB_PORT=5432
    restart: on-failure
    depends_on:
      - postgres
    networks:
      custom_network:
        ipv4_address: 172.19.0.3

  websocket:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    container_name: websocket
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=flask_app.py
      - FLASK_RUN_HOST=0.0.0.0
      - EXPERIMENT_NAME=watsonx_insurance_claims_experiment
      - GRAPHSIGNAL_API_KEY=7e6ff4494810b4cb37255d369cfae983
      - OPENAI_API_KEY=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
      - API_URL=http://172.19.0.3:3001
      - OPENAI_ORG_ID=org-zvKGqHl0adRlJbe7lpb7n1wX
      - DB_HOST=172.19.0.2
      - REACT_APP_WEBSOCKET_URL=ws://172.19.0.4:8080
      - REACT_APP_API_URL=http://172.19.0.3:3001
      - FLASK_SERVER_URL=http://172.19.0.3:3001
      - DB_NAME=roja_postgres
      - DB_USER=roja_user
      - DB_PASSWORD=roja_user
      - DB_HOST=172.19.0.2
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      custom_network:
        ipv4_address: 172.19.0.4

  client-app:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3001:80"
    environment:
      - FLASK_APP=flask_app.py
      - FLASK_RUN_HOST=0.0.0.0
      - EXPERIMENT_NAME=watsonx_insurance_claims_experiment
      - GRAPHSIGNAL_API_KEY=7e6ff4494810b4cb37255d369cfae983
      - OPENAI_API_KEY=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
      - API_URL=http://172.19.0.3:3001
      - OPENAI_ORG_ID=org-zvKGqHl0adRlJbe7lpb7n1wX
      - DB_HOST=172.19.0.2
      - REACT_APP_WEBSOCKET_URL=ws://172.19.0.4:8080
      - REACT_APP_API_URL=http://172.19.0.3:3001
      - FLASK_SERVER_URL=http://172.19.0.3:3001
      - DB_NAME=roja_postgres
      - DB_USER=roja_user
      - DB_PASSWORD=roja_user
      - DB_HOST=172.19.0.2
      - DB_PORT=5432
    depends_on:
      - websocket
    networks:
      custom_network:
        ipv4_address: 172.19.0.5

volumes:
  pgdata:
    driver: local

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

