name: SonarQube Scan

on:
  push:
    branches:
      - ci_automation
  pull_request:
    branches:
      - ci_automation

jobs:
  sonarqube:
    runs-on: self-hosted  
    steps:
      - run: echo "Runner is working!"
  
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarQube scanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Ai-observability-metrics \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

